dist: trusty
sudo: enabled
group: deprecated-2017Q4
language: c

branches:
  only:
  - master
  - coverity_scan

env:
  global:
    - CHECKPATCH_INSTALL="$HOME/builds/checkpatch-install"
    - secure: icWgMUsP+/63P2ago4iGLM8lMcYoMebPeW6mKb/qVfzLB1hRzbn3YB2X6ieprfAybIAd3zXpbrbSW1KCDyycRuSY57aBKqUDJbjGeRNQNPEsmDK+8ZGtSNY3TbRkidcNd/GnNCygLi4Xewmk7TghSAkcKCM3WF+xjqtqCJYV4bMqXhdK6w5x/NljF+aD2l7vBNEUNTyipkGKcdvXDx5k5LVJ++Zwr4wuKuxg5iSonaz06ROowCsA1T0PxeFqmYRatp0Q9lonCJ0GiLVXfPBQLfaXHJMn5Qk7S5WIfwfQoCQu7mbpqR9MQAPcWqPv39yNMgOVl2c98B/z/Ffz5vJQ3Xz/WTID23Ia9RMfkE4s4LnwZ+Tl15oHQaI4t81o+Q6YWk3VhpIMoLfvnNyfRsAUgdw0Ydme8RoKFlzHPjS7p34+M0q2X/egAiyWz0akydWb/HjBkNoPFSnxwzLBwKMLSy0YfRvssb0kVBCi7ywLl6tLARlTqUbdA0GyCg7jWPjbMr5QRe/3hT9zQBugLtT0EbYOwe2BxCcUlcRqu6Kx3f4wv3uKPCsQgFo+NkulBrBHKU+OKrOh6/gujdgNzfxCVMa+MlvNQ12RWdsm5qS8hQV5VrwPa/q3GIDpEBltc9WPQ9vYmKfctHLpCsDcJWgLIWgppHkR5dLGFP2TSMMRbHk=

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; else brew update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install openvpn -y; else brew install openvpn openssl; fi
  - "./ci/install_deps.sh"

addons:
  coverity_scan:
    project:
      name: riboseinc/rvc
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command: make -j4
    branch_pattern: coverity_scan

after_failure: cat tests/test-suite.log

install:
  - "./ci/install.sh"

script:
  - "./ci/main.sh"

os:
  - linux
  - osx
