= RVC: the **R**elaxed **V**PN **C**lient

RVC is a command-line driven OpenVPN client for macOS (Sierra and High
Sierra) and (WIP: RHEL/CentOS 7 + Ubuntu) with two focus areas:

* CLI usage for automation
* Security for protection of your OpenVPN private keys + certificates
  and ensuring that only approved routes are added to your route table

Don't get fooled by the word *Relaxed*. It is meant that you can relax
when using RVC and not having to stress about your VPN private keys and
certificates getting compromised.

NOTE1: Let us know if you have any comments, suggestions for improvement,
found a bug or identified a security vulnerability.

NOTE2: We are open to pull requests!


== Quick Install

On macOS:

[source,sh]
----
brew tap riboseinc/rvc
brew install --HEAD rvc
sudo /usr/local/bin/rvc_install.sh
----

WARNING: **Remember to follow instructions given in the "caveats" section during `brew install`!**

NOTE: Take a look at the https://github.com/riboseinc/homebrew-rvc[RVC
  homebrew formula] if you want to know more.


On RHEL/CentOS:

[source,sh]
----
sudo yum install https://github.com/<TODO>
----


== Usage

[source,console]
----
$ rvc
usage: rvc <options>
  options:
    <all|connection name> connect [--json]	connect to a VPN with given name
    <all|connection name> disconnect [--json]	disconnect VPN with given name
    <all|connection name> reconnect [--json]	reconnect VPN with given name
    [all|connection name] status [--json]	get status of VPN connection with given name
    <connection name> edit <auto-connect|pre-exec-cmd|profile> <value>
    <connection name> remove [--force]		remove VPN connection (sudo required)
    import <new-from-tblk|new-from-ovpn> <path>	import VPN connection (sudo required)
    reload					reload configuration (sudo required)
    dns-override <enable|disable|status> [DNS server IP list]
           override DNS settings. DNS server IP addresses should be separated by comma (sudo required)
    script-security <enable|disable>		enable/disable script security
    help					show help message
    version					print version
----


=== Add VPN Connection

Follow these steps to setup a new VPN connection. The name of the VPN
is derived from the filename.

Add the OpenVPN configuration (a `.ovpn` file):

[source,sh]
----
sudo vi /opt/rvc/etc/vpn.d/vpn1.ovpn
----

Example OpenVPN file (with empty `<cert>`, `<ca>` and `<key>`, these
obviously needs to be in there when actually adding the VPN):

.<RVC path>/etc/vpn.d/vpn1.ovpn
[source]
----
client
dev tun
proto tcp
remote 10.1.1.1 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
comp-lzo
verb 3
auth SHA512
cipher AES-256-CBC
tls-version-min 1.2

<ca>
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
</key>
----


(**OPTIONAL**) Add the JSON configuration:

[source,sh]
----
sudo vi /opt/rvc/etc/vpn.d/vpn1.json
----

.<RVC path>/etc/vpn.d/vpn1.json
[source,json]
----
{
  "auto-connect": false,
  "pre-connect-exec": "",
  "pre-connect-exec-interval": ""
}
----

Set the correct permissions on both files:

[source,sh]
----
sudo chmod 500 /opt/rvc/etc/vpn.d/vpn1.ovpn
sudo chmod 500 /opt/rvc/etc/vpn.d/vpn1.json
----

After adding the new VPN called `vpn1` by adding the `.ovpn` + `.json` files
to `<RVC path>/etc/vpn.d` you need to reload `rvd`.

Reload `rvd`:

[source,console]
----
$ sudo rvc reload
Sending reload signal to rvd process '3667' has succeeded.
----

Check status:

[source,console]
----
$ rvc vpn1 status
name: vpn1
	config-status: JSON configuration exists
	profile: /opt/rvc/etc/vpn.d/vpn1.ovpn
	status: DISCONNECTED
	openvpn-status: DISCONNECTED
	in-total: 0
	out-total: 0
	timestamp: 1512720431
	auto-connect: Disabled
	pre-exec-cmd:
	pre-exec-status:
	pre-exec-interval:

----


=== Connect A VPN Connection

[source,console]
----
$ rvc vpn1 connect
name: vpn1
	config-status: JSON configuration exists
	profile: /opt/rvc/etc/vpn.d/vpn1.ovpn
	status: CONNECTING
	openvpn-status: DISCONNECTED
	in-total: 0
	out-total: 0
	timestamp: 1512720713
	auto-connect: Disabled
	pre-exec-cmd:
	pre-exec-status:
	pre-exec-interval:

$ rvc vpn1 status
name: vpn1
	config-status: JSON configuration exists
	profile: /opt/rvc/etc/vpn.d/vpn1.ovpn
	status: CONNECTED
	openvpn-status: CONNECTED
	in-total: 2293
	out-total: 2419
	connected-time: 1512720716
	in-current: 2293
	out-current: 2419
	timestamp: 1512720719
	auto-connect: Disabled
	pre-exec-cmd:
	pre-exec-status:
	pre-exec-interval:

----


=== Check Status Of A VPN Connection

[source,console]
----
$ rvc vpn1 status
name: vpn1
	config-status: JSON configuration exists
	profile: /opt/rvc/etc/vpn.d/vpn1.ovpn
	status: CONNECTED
	openvpn-status: CONNECTED
	in-total: 3036
	out-total: 3153
	connected-time: 1512720716
	in-current: 3036
	out-current: 3153
	timestamp: 1512720769
	auto-connect: Disabled
	pre-exec-cmd:
	pre-exec-status:
	pre-exec-interval:

----


=== Disconnect A VPN Connection

[source,console]
----
$ rvc vpn1 disconnect
name: vpn1
	config-status: JSON configuration exists
	profile: /opt/rvc/etc/vpn.d/vpn1.ovpn
	status: DISCONNECTING
	openvpn-status: CONNECTED
	in-total: 3226
	out-total: 3358
	timestamp: 1512720820
	auto-connect: Disabled
	pre-exec-cmd:
	pre-exec-status:
	pre-exec-interval:

$ rvc vpn1 status
name: vpn1
	config-status: JSON configuration exists
	profile: /opt/rvc/etc/vpn.d/vpn1.ovpn
	status: DISCONNECTED
	openvpn-status: DISCONNECTED
	in-total: 3226
	out-total: 3358
	timestamp: 1512720824
	auto-connect: Disabled
	pre-exec-cmd:
	pre-exec-status:
	pre-exec-interval:

----


== Structure

RVC has the following structure:

* `<RVC path>/bin/rvd`: the daemon that is responsible for starting and
  stopping VPN connections
* `<RVC path>/bin/rvc`: the client that is used to make `rvd`
  connect/disconnect to VPNs
* `<RVC path>/etc/rvd.conf`: the main configuration file for `rvd`
* `<RVC path>/etc/vpn.d`: the directory in which `.ovpn` and `.json` files are
  stored
* `/var/run/rvd`: the socket that `rvc` uses to communicate with `rvd`
* `/var/log/rvd/rvd.log`: the log file from `rvd`, use this for
  troubleshooting

Mandatory VPN configuration files:

* `<RVC path>/etc/vpn.d/<vpn>.ovpn`: the OpenVPN file that contains the
  configuration of the VPN, private key, client certificate and CA
  certificate

Optional VPN configuration files:

* `<RVC path>/etc/vpn.d/<vpn>.json`: the `rvd` configuration of this
  particular VPN

VPN log files:

* `/var/log/rvd/<vpn>.ovpn.log`: VPN log file


=== Platform Specific Paths and Dependencies: macOS

RVC path::
  `/opt/rvc`

`launchd` `rvd` plist::
  `/Library/LaunchDaemons/com.ribose.rvd.plist`

Dependencies:

* `/opt/openvpn/sbin/openvpn`: a copy of the OpenVPN executable that is
  owned by `root`


=== Platform Specific Paths and Dependencies: RHEL/CentOS

RVC path::
  `/usr/local`

`systemd` unit file::
  `/lib/systemd/system/rvd.service`

Dependencies:

* `/usr/sbin/openvpn`: the location of the OpenVPN executable as installed via `yum`


== Configuration

=== Global Configuration

The `<RVC path>/etc/rvd.json` configuration file looks like this on macOS:

.<RVC path>/etc/rvd.json
[source,json]
----
{
  "openvpn_bin": "/opt/openvpn/sbin/openvpn",
  "openvpn_root_check": true,
  "ovpn_up_down_scripts": false,
  "user_id": 501,
  "restrict_socket": true,
  "log_directory": "/var/log/rvd.log",
  "vpn_config_paths": "/opt/rvc/etc/vpn.d"
}
----


`openvpn_bin`::
  the location of the OpenVPN executable. Since this executable will run
  as `uid 0` it is important to place this executable in a directory not
  writable by unprivileged users.
+
NOTE: On macOS OpenVPN will be most likely installed by `brew` in
  `/usr/local/sbin` and for security purposes therefore must be copied
  to `/opt/openvpn/sbin`. If you wish to have `rvd` use the OpenVPN
  executable in `/usr/local/sbin` then you can, **but this is not
  advised as a local attacker typically can replace anything in `/usr/local/`**.

`openvpn_root_check`::
  `rvd` can perform a check whether the OpenVPN executable is owned by
  root. On macOS `rvd` will expect OpenVPN to live in
  `/opt/openvpn/sbin` which must be owned by root. In case you want to
  use the OpenVPN executable in another directory such as
  `/usr/local/bin` then you can disable this check, **but this is not
  advised**.

`ovpn_up_down_scripts`::
  OpenVPN allows to run up and down scripts to set routes and perform
  MFA actions. By default this behaviour is disabled and up scripts are
  handled by `rvd` on a per VPN basis with the `pre-connect-exec`
  statement in the VPN .json file. **It is not advised to enable the
  `ovpn_up_down_scripts` globally unless you really need this and know
  what you are doing.**

`user_id`::
  this is the UID of the unprivileged user `rvd` will execute
  `pre-connect-exec` scripts as. Also the socket of `rvd` will only be
  writable to by this UID.

`restrict_socket`::
  `rvd` by default only accepts `rvc` socket connections from the UID
  set in `user_id`. This is to prevent access to your VPN connections on
  multi-user systems. **Disabling this restriction is not advised.**

`log`::
  this is the log file `rvd` will write to.

`vpn_config_paths`::
  `rvd` stores OpenVPN files on macOS in `/opt/rvc/etc/vpn.d` and on
  RHEL/CentOS in `/usr/local/etc/vpn.d/`.

This file is **mandatory**.


=== Per-VPN Configuration

Example `rvd` configuration for a VPN: `<RVC path>/etc/vpn.d/vpn1.json`.

.<RVC path>/etc/vpn.d/vpn1.json
[source,json]
----
{
  "auto-connect": false,
  "pre-connect-exec": ""
  "pre-connect-exec-interval": ""
}
----

This file is **optional**.


`auto-connect`::
  Set this to `true` when you want to automatically connect to a VPN
  when `rvd` starts. This is useful when you have Jenkins slaves auto
  connecting to VPNs upon boot.

`pre-connect-exec`::
  Run a script or executable before connecting to the VPN. This can be
  used to execute a script for MFA purposes.

`pre-connect-exec-interval`::
  Repeat the execution of the `pre-connect-exec` at set intervals. This
  is useful for continuous MFA keep alive. 

The `.json` configuration file for a VPN is *optional*. You should only
create one if you need `auto-connect` and/or a `pre-connect-exec` script
to run.


== Security Architecture And Considerations

The architecture of RVC is designed to be seamlessly used and managed
from the command line, but kept as secure as possible.

You need `sudo` for operations that require access to root owned
directories and files.

NOTE: macOS clients are typically GUI based and require you to enter a
password every time you want to change something. This approach makes it
impossible to automate VPN management and operation. RVC is created
to fix this for macOS OpenVPN connection management.


=== Architecture

----
+-----------------+
| launchd/systemd |
+-+---------------+
  |
  v
+--------------------+  +-main configuration------+
| <RVC path>/bin/rvd +->| <RVC path>/etc/rvd.json |
+-+----+-------------+  +-------------------------+
  |
  |        +-rvd VPN configuration file------+
  |     +->| <RVC path>/etc/vpn.d/<vpn>.json |
  |     |  +---------------------------------+
  +-----+
  |     |  +-OpenVPN configuration file------+
  |     +->| <RVC path>/etc/vpn.d/<vpn>.ovpn |<-+
  |        +---------------------------------+  |
  |                                             |
  |      +-rvd log--------------+          +----+
  +----->| /var/log/rvd/rvd.log |          |
  |      +----------------------+          |
  |                                        |
  |      +-OpenVPN started by rvd----------+-------------------------------+
  +----->| <OpenVPN path>/openvpn --config <RVC path>/etc/vpn.d/<vpn>.ovpn |
  |      +                        --log-append /var/log/rvd/<vpn>.ovpn.log |
  |      +-------------------------------------+---------------------------+
  |                                            |
  |                        +-------------------+
  |                        |
  |      +-socket-------+  |  +-VPN log file----------------+
  +----->| /var/run/rvd |  +->| /var/log/rvd/<vpn>.ovpn.log |
         +--------------+     +-----------------------------+
           ^
           |
+----------+---------+
| <RVC path>/bin/rvc +
+--------------------+
----


=== RVD Binary Ownership

`rvd` is owned by `root:wheel` and has the following permissions:
`-r-x------`. `rvd` is meant to be only executed by `launchd` or
`systemd`. So don't start it manually. Upon starting `rvd` will create a
socket in `/var/run/rvd` which will be writable only by a predefined
userid that is set in `<RVC path>/etc/rvd.conf`.

It looks like this:

[source,console]
----
$ ls -la /var/run/rvd
srw-------  1 test  wheel  0 Sep 19 15:52 /var/run/rvd
$ id test
uid=501(test) gid=20(staff) groups=20(staff),401(com.apple.sharepoint.group.1),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),501(access_bpf),701(com.apple.sharepoint.group.3),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),402(com.apple.sharepoint.group.2)
----


=== RVC Binary Ownerships

`rvc` is owned by `root:wheel` and has the following permissions:
`-r-xr-xr-x`. `rvc` can be executed by any user but the socket `rvc`
connects to can only be written to a predefined userid. This restricts
the connecting/disconnecting of VPNs to a single userid. Sending a
`reload` signal to `rvd` using `rvc` requires `sudo`.

On macOS Brew and/or a manual `make install` installs `rvc` to
`/usr/local/bin`, you **MUST** follow the instructions to install the
executables in `/opt/rvc/bin` using `rvc_install.sh`.

`rvc` performs a check whether it is executed from `/opt/rvc/bin` or
not. If it isn't then it will exit. This will force you to put
`/opt/rvc/bin` in the beginning of your `PATH`. This is to prevent you
from running `sudo` on a backdoored `rvc` that was placed in
`/usr/local/bin` by a local attacker.


=== OpenVPN Files

OpenVPN configuration files are stored in `<RVC path>/etc/vpn.d` which
is owned by `root:wheel` and has `drwxr-xr-x` permissions.

The per-connection OpenVPN files are stored as
`<RVC path>/etc/vpn.d/<vpn>.ovpn`, owned by `root:wheel` and have
`-rw-------` permissions.

The `rvd` VPN configuration are stored as
`<RVC path>/etc/vpn.d/<vpn>.json`, owned by `root:wheel` and have
`-rw-------` permissions.

This strict permission and owner scheme is to prevent your private keys
being leaked and/or your VPN configurations modified by a local
attacker.

If `rvd` were to be allowed to use *any* OpenVPN file then a local
attacker could potentially change the routes to the system's DNS servers
to an attacker controlled IP.

`rvd` *only* accepts OpenVPN files that are owned by `root` and are not
readable by `others`:

[source,console]
----
$ ls -la /opt/rvc/etc/vpn.d
total 144
drwxr-xr-x  14 root  wheel   476 Sep 15 13:28 .
drwxr-xr-x   4 root  wheel   136 Sep 15 16:48 ..
-rw-------   1 root  wheel   146 Sep 11 13:50 vpn1.json
-rw-------   1 root  wheel  7240 Sep 11 13:50 vpn1.ovpn
----


=== Per-VPN Configuration

VPNs do not not require a .json `rvd` configuration file. By default
VPN connections will not `auto-connect` and no `pre-connect-exec` will
be executed.


=== Pre-Connect Scripts

VPNs can be configured that a script is executed before OpenVPN will
connect. This is defined in `pre-connect-exec` in
`<RVC path>/etc/vpn.d/<vpn>.json`.

As `rvd` runs as `root` it will drop its root privileges to the UID
defined with `user_id` in `<RVC path>/etc/rvd.json`.


=== Log Files

OpenVPN will be executed as root but log files will be owned by
`user_id`. This is to ensure that your desktop user can access and
delete the log files of his/her VPNs.

The following code in `src/vpn.c` is responsible for this:


=== OpenVPN Executable

On macOS Brew installs OpenVPN in `/usr/local/sbin`. This allows a local
attacker to replace the `openvpn` executable with something malicious.
Therefore during installation of RVC a root-owned copy of `openvpn`
needs to be placed in `/opt/openvpn/sbin`.

Upon start, `rvd` will perform the `root` check on the `openvpn`
executable before it actually runs it.


== Development

=== Installation via source on macOS

Install dependencies:

[source,sh]
----
brew install openvpn
----

Manual compilation and installation:

[source,sh]
----
git clone https://github.com/riboseinc/rvc
cd rvc
./build_macos.sh
make install
sudo /usr/local/bin/rvc_install.sh
----


