= rvc

The Ribose VPN Client.

This is like Tunnelblick but we found Tunnelblick too heavy and not
configurable via the command line (with unnecessary UI prompts).


== Configuration file

The global configuration file must be in: '~/.setup/vpn/vpn.json' and should be based on the following (json format):

[source,json]
----
[
  {
    "name": "staging foobar.baz",
    "ovpn": /Users/test/.setup/vpn/test@foobar.baz-staging.ovpn",
    "connect": "true"
  },
  {
    "name": "testing foobar.baz",
    "ovpn": /Users/test/.setup/vpn/test@foobar.baz-testing.ovpn",
    "connect": "false"
  }
]
----

The script loops through 'vpn.json' and does the following:

1. Checks whether OpenVPN is installed and properly set up, in case it's not installed or properly set up then display some hints on how to install / set up
2. Check whether the endpoints needs to be connected or not
3. Checks whether the '.ovpn' file is sane (contains the correct configuration and that all keys and certificates are present)
4. Based upon the value of 'connect' it connects or disconnects the OpenVPN connection (start/stop OpenVPN for the endpoint)


== CLI

The script can be started/used in the following methods:

[source,bash]
----
rvc [command] [options] <vpn-name>
----

Options:
* `--json` gives output in JSON format.
* `--all` applies to all preferred VPNs (where `connect: true`)

1. `rvc connect --all` connects all configured VPNs that have `connect` set to `true`
2. `rvc connect <VPN name>` where VPN name is the `name` property as configured in `vpn.json`, with the longest match.
a. Example: In `vpn.json` there is `name: "testing foobar.baz"`, to connect we could then run: `rvc c testing` or `rvc c "testing foobar.baz"`.
3. `rvc kill --all` kills all VPN connections
4. `rvc kill <VPN name>` kills a single VPN connection in a similar fashion like #2
5. `rvc status` shows the status of all VPN connections (connected and not connected)
6. `rvc status <VPN name>` shows the status of a single VPN connection in a similar fashion like #2



== GUI

The GUI is an icon in the macOS Menu Bar. It should expand/unfold when clicked
on it.

The GUI status monitor displays each configured VPN (via 'vpn.json') with the
status [not connected: grey] or [connected: green] based on the actual OpenVPN
process status. At the bottom of the list of configured VPNs there is a toggle
switch to connect and disconnect all VPNs that have 'connect' set to true:


== Launchd

Create a launchd file with the following properties:

* start GUI status monitor after the login of the user
* when killed (crash or by command line) automatically respawn

== Technical specifications

* The connecting script is written in bash and it needs to run on macOS and needs to follow Google's shell style (https://google.github.io/styleguide/shell.xml). Obviously the GUI is not in bash.
* The script should not run as root where possible. If root privileges are needed (e.g.: for OpenVPN) then 'sudo' needs to be used
* The location of the script and GUI is in /usr/local/bin
* Error logging should be done to syslog


